#The name of your workflow.
name:  Test, build and deploy
# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:

  test:
    #The type of machine to run the job on. [windows, macos, ubuntu , self-hosted]
    runs-on: macos-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.14'
          channel: 'dev'
      - run: flutter pub get
      # run static analyse code
      - run: flutter  analyze
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage

  build_deploy:
    #if conditional to prevent a job from running
    if: github.event_name != 'pull_request'
    runs-on: macos-latest
    #Identifies any jobs that must complete successfully before this job will run.
    needs: test
    name: Build  apk  and web
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.14'
          channel: 'stable'
      # This action sets up a java environment
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter build apk --debug --split-per-abi
      # This action will create a github release and optionally upload an artifact to it.
      # https://github.com/ncipollo/release-action
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}
